Add basic implementation
thegreathir/piggame pull request #1
Opened 2023-04-03 09:24 UTC by thegreathir

2023-04-03 18:36 UTC, HKalbasi requested changes

2023-04-03 18:36 UTC, HKalbasi commented on src/main.rs
> +}
این شکلی بهتر نیست؟:
```Rust
enum GameState {
    Playing(PlayingGame),
    New(NewGame),
}
struct PlayingGame {
    players: HashMap<i64, Player>,
    turn: u8,
    current_score: u8,
}
struct NewGame {
     players: HashMap<i64, Player>,
}
```
بعد متد های مربوط به هر کدوم می تونه جدا بشه، و دیگه مثلا وقتی که بازی هنوز شروع نشده نمی تونیم اشتباهی ترن و اینا رو خراب کنیم.

2023-04-03 18:36 UTC, HKalbasi commented on src/main.rs
> +    }
این غلطه. ترتیب خروجی ایتریتور هش مپ استیبل نیست. ولی اگه غلط نبود هم بی خودی وکتور ساخته بود. می تونست با enumerate و find هندل کنه همین کاری که الان داره می کنه رو.

2023-04-03 18:36 UTC, HKalbasi commented on src/main.rs
> +}
و می شه مثلا توی پلینگ گیم لیست بازیکنا وکتور باشه ولی توی نیو گیم هش مپ باشه

2023-04-03 18:36 UTC, HKalbasi commented on src/main.rs
> +            _ => (),
این جا نباید به یارو یه چیزی بگیم که چرت پیام داده یا یه هم چین چیزی؟

2023-04-03 18:36 UTC, HKalbasi commented on src/main.rs
> +            .unwrap()
این حس می کنم زیاد جالب نیست. یه کریت توی کریتس آی او نیست که استراکت های مربوط به ای پی آی تلگرام رو تعریف کرده باشه؟ بعد سرده دیسریالایز رو روی اون صدا می کنی و دیگه از اون به بعد اون خودش فیلد چت و اینا داره.

اگه توی کریتس آی او نیست یا نمی خوای استفاده کنی، می تونی خودت تعریفش کنی. باید یه استراکت بسازی که یه فیلد چت داشته باشه که اون یه فیلد آی دی داشته باشه (و بقیه فیلد های مربوط). بعدش توی دیسریالایز کردن یه بار به جای همه این آنرپ ها می تونی آنرپ کنی یا حتی بهتر از اون، آن رپ نکنی، مثلا سعی کنی به ادمین پیام بدی که ای پی آی تلگرام تغییر کرده یا یه هم چین چیزی.

2023-04-03 18:36 UTC, HKalbasi commented on src/main.rs
> +                self.hold(message_info.sender_id).unwrap();
این جا مطمئنی می خوای پنیک کنی اگه اررور بود؟ با پنیک کلا سرورت بسته می شه. کلا کل استفاده های آنرپ توی کدت یا مشکوکه یا غلطه از نظر من.

2023-04-03 18:36 UTC, HKalbasi commented on src/main.rs
> +    let bot_token: String = env::var("BOT_TOKEN").unwrap();
مثلا این آنرپ معقولیه. ولی بقیه آنرپا مشکوکن. حتی این هم که معقوله، می تونی به جاش از expect استفاده کنی تا اررور با متن دلخواهتو به کسی که سرور رو اجرا می کنه بدی (البته خود اررور env::var هم معقول می ده فک کنم.)

2023-04-14 14:04 UTC, thegreathir commented on src/main.rs
> +}
انجام شد

2023-04-14 14:04 UTC, thegreathir commented on src/main.rs
> +    }
این رو حل کردم
شافل رو هم اضافه کردم

2023-04-14 14:05 UTC, thegreathir commented on src/main.rs
> +            _ => (),
نه خیلی شلوغ می‌شه چت
تجربه‌کاربریش کلاً بد نیست حالا فاز داشتی یه گروه می‌زنیم تست می‌کنیم :))
یا توو یه گروه خودت اضافه کن بالا اوردمش

2023-04-14 14:05 UTC, thegreathir commented on src/main.rs
> +            .unwrap()
انجام شد
همه رو نوشتم خودم و خیلی کد کوچیک شد دستت درد نکنه

2023-04-14 14:06 UTC, thegreathir commented on src/main.rs
> +                self.hold(message_info.sender_id).unwrap();
حذف شد این تیکه و یه جور دیگه نوشته شد

2023-04-14 14:07 UTC, thegreathir commented on src/main.rs
> +    let bot_token: String = env::var("BOT_TOKEN").unwrap();
یه بار دیگه نگاه کن کلاً خیلی کم شد تعداد آن‌رپ‌ها...

2023-04-14 15:21 UTC, hkalbasi commented on src/game_model.rs
> +    fn from(new_game: &NewGame) -> PlayingGame {
این می تونه تریت فرام رو ایمپلمنت کنه. خیلی فرقی نمی کنه صرفا `.into()` رو فعال می کنه و می شه تو تابع هایی که جنریکن استفاده کرد.

2023-04-14 15:21 UTC, hkalbasi commented on src/game_model.rs
> +        let mut players: Vec<Player> = new_game.players.values().cloned().collect();
این کلون لازمه؟ نمی شد این تابع بدون رفرنس بگیره نیو گیم رو؟

2023-04-14 15:21 UTC, hkalbasi commented on src/game_model.rs
> +                Ok((result, playing_game.get_current_player().clone()))
این کلون های پلیر خیلی جالب نیست. هم هزینه پرفورمنسی داره، هم این که ممکنه به جای این که یه چیزی رو تغییر بدی کلونش رو تغییر بدی. حس می کنم درست این جا این باشه که به جای این که پلیر پاس بدی به تابع هات، آی دی پلیر رو پاس بدی.

بعد ممکنه بگی پاس دادن یه سری `u64` خیلی زشته، که درسته. باید یه رپر تایپ مثل `struct PlayerId(u64)` تعریف کنی بعد اونو این ور اون ور پاس بدی که تایپ سیف بشه. که توی این حالت خاص کریت `la_arena` همین کارو می کنه.

2023-04-14 15:21 UTC, hkalbasi commented on src/game_model.rs
> +                        Err(GameLogicError::JoinAfterPlay) => {
اینا برن توی یه متد روی `GameLogicError` بهتر نیست؟

2023-04-14 15:21 UTC, hkalbasi commented on src/telegram_types.rs
> +    pub entity_type: String,
این و اون `chat_type` استفاده می شن؟ اگه آره بهتره به جای استرینگ عینام باشن. اگه نه، می تونی حذفشون کنی و تو دیسریالایز ایگنور می شه.

2023-04-14 15:21 UTC, HKalbasi commented on src/main.rs
> +async fn send_message(bot_token: &str, target_chat: i64, text: String, reply: Option<i64>) {
یه تابع جدا برای ریپلای داشته باشیم بهتر نیست؟ اینا دیگه سلیقه ایه.

2023-04-14 15:21 UTC, HKalbasi commented on src/main.rs
> +async fn remove_inline_keyboard(bot_token: &str, target_chat: i64, text: String, message_id: i64) {
اینا هم نرن تو تلگرام تایپس؟

2023-04-14 15:21 UTC, HKalbasi commented on src/game_model.rs
> +        self.players.get_mut(self.turn as usize).unwrap()
اینم معادل `&mut self.players[self.turn as usize]` عه. معمولا به جای گت و آنرپ پشت هم ایندکس استفاده می شه.

2023-04-14 15:21 UTC, HKalbasi commented on src/main.rs
> +    client.post(end_point).json(&body).send().await.unwrap();
این سرور رو بیاره پایین اوکیه؟ کی فیل می شه؟

2023-04-14 15:21 UTC, HKalbasi commented on src/telegram_types.rs
> +    pub dice: Option<Dice>,
سریالایز این درست کار می کنه؟ یا اصن استفاده نمی شه؟

2023-04-19 17:13 UTC, HKalbasi commented on src/game_model.rs
> +    fn get_playing_game(&self) -> Option<&PlayingGame> {
اینا مستقیم ریزالت برنگردونن که دیگه لازم نباشه ok_or بزنی بعدا؟

2023-04-19 22:39 UTC, thegreathir commented on src/main.rs
> +    client.post(end_point).json(&body).send().await.unwrap();
حلش کردم

2023-04-19 22:39 UTC, thegreathir commented on src/telegram_types.rs
> +    pub dice: Option<Dice>,
مشکلش چیه؟

2023-04-19 22:39 UTC, thegreathir commented on src/game_model.rs
> +    fn from(new_game: &NewGame) -> PlayingGame {
خب این‌جا به چه درد من می‌خوره؟
یعنی لازم شد می‌ذارمش دیگه؟

2023-04-19 22:39 UTC, thegreathir commented on src/game_model.rs
> +        let mut players: Vec<Player> = new_game.players.values().cloned().collect();
این رو ردیف کردم
کلاً کلون پلیر پاک کردم

2023-04-19 22:39 UTC, thegreathir commented on src/game_model.rs
> +                Ok((result, playing_game.get_current_player().clone()))
پاک کردم کلون‌های پلیر رو یه نگاه بکن

2023-04-19 22:39 UTC, thegreathir commented on src/game_model.rs
> +                        Err(GameLogicError::JoinAfterPlay) => {
نفهمیدم چیا؟

2023-04-19 22:39 UTC, thegreathir commented on src/telegram_types.rs
> +    pub entity_type: String,
نفهمیدم خب سریالایز می‌شه این

باید اون اینامه رو دیسپلی کنم؟

2023-04-19 22:39 UTC, thegreathir commented on src/main.rs
> +async fn send_message(bot_token: &str, target_chat: i64, text: String, reply: Option<i64>) {
عوض شد کلاً

2023-04-19 22:39 UTC, thegreathir commented on src/main.rs
> +async fn remove_inline_keyboard(bot_token: &str, target_chat: i64, text: String, message_id: i64) {
چیا؟
پاک شد کلیش تقریباً

2023-04-19 22:39 UTC, thegreathir commented on src/game_model.rs
> +        self.players.get_mut(self.turn as usize).unwrap()
درستش کردم

2023-04-19 23:24 UTC, HKalbasi commented on src/telegram_types.rs
> +    pub dice: Option<Dice>,
من حس می کنم دایس سریالایزش چرت می شه ولی این استراکت رو سریالایز نمی کنی اصلا.

2023-04-19 23:31 UTC, hkalbasi commented on src/message_action.rs
> +    pub message_id: i64,
اینا رو هم می خوای نیو تایپ بزاری براشون؟ یعنی یه استراکت تعریف کنی این شکلی
```Rust
#[derive(Serialize)]
#[serde(transparent)
pub struct MessageId(i64);
```
این شکلی جلوت از این که اشتباهی مثلا یه یوزر آی دی رو به جای مسیج آی دی استفاده کنی گرفته می شه.

2023-04-19 23:31 UTC, HKalbasi commented on src/telegram_types.rs
> +    pub emoji: String,
اینم بده حس می کنم. چرا ایموجی رو نگه می داری؟ دایس تایپ رو نگه دار.

2023-04-20 09:17 UTC, thegreathir commented on src/game_model.rs
> +                        Err(GameLogicError::JoinAfterPlay) => {
انجام شد

2023-04-20 10:30 UTC, merged